environment:
  gateway_url:  http://gateway.openfaas:8080/
  gateway_public_url: https://cloud.o6s.io/
  audit_url: http://gateway.openfaas:8080/function/audit-event
  repository_url: docker.io/ofcommunity/
  push_repository_url: docker.io/ofcommunity/
  basic_auth: true
  secret_mount_path: /var/openfaas/secrets
  builder_url: http://of-builder.openfaas:8080/

# To use a shared Docker Hub account.
#  repository_url: docker.io/ofcommunity/
#  push_repository_url: docker.io/ofcommunity/

# Private repo config
# repository_url: 127.0.0.1:5000
# push_repository_url: registry:5000
